#!/usr/bin/env python3
"""
KeeLoq Groebner Basis Solver using passagemath

This script models KeeLoq as a system of polynomial equations over GF(2)
and solves for the secret key using Groebner basis computation.

Supports two modes:
1. Default: Generate equations using Python implementation
2. --use-polygen: Use equations generated by the C polygen implementation

Requirements:
    pip install passagemath-standard
    
    Or for a minimal install:
    pip install passagemath-brial passagemath-singular

Usage:
    python groebner_solver.py [--rounds N] [--pairs N] [--use-polygen]

Author: H. Hadipour
"""

import argparse
import os
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional, List, Tuple

# Check for passagemath/sage availability
try:
    from sage.all import GF, BooleanPolynomialRing, Ideal
    SAGE_AVAILABLE = True
except ImportError:
    SAGE_AVAILABLE = False
    print("=" * 60)
    print("ERROR: passagemath/SageMath not found")
    print("=" * 60)
    print("\nInstall with one of:")
    print("  pip install passagemath-standard")
    print("  pip install sage")
    print("  conda install sage")
    print("\nOr visit: https://github.com/passagemath/passagemath")
    print("=" * 60)


# KeeLoq NLF lookup constant
NLF_CONSTANT = 0x3A5C742E


def nlf(x4: int, x3: int, x2: int, x1: int, x0: int) -> int:
    """KeeLoq Non-Linear Function (5-input, 1-output)."""
    index = (x4 << 4) | (x3 << 3) | (x2 << 2) | (x1 << 1) | x0
    return (NLF_CONSTANT >> index) & 1


def keeloq_encrypt(key: int, plaintext: int, rounds: int = 528) -> int:
    """KeeLoq encryption (for verification)."""
    state = plaintext
    for i in range(rounds):
        nlf_out = nlf(
            (state >> 31) & 1,
            (state >> 26) & 1,
            (state >> 20) & 1,
            (state >> 9) & 1,
            (state >> 1) & 1,
        )
        key_bit = (key >> (i % 64)) & 1
        feedback = key_bit ^ ((state >> 16) & 1) ^ (state & 1) ^ nlf_out
        state = ((state >> 1) | (feedback << 31)) & 0xFFFFFFFF
    return state


def create_nlf_polynomial(ring, x4, x3, x2, x1, x0):
    """
    Create algebraic normal form (ANF) of the KeeLoq NLF.
    
    NLF(a,b,c,d,e) = d + e + ac + ae + bc + be + cd + de + ade + ace + abd + abc
    
    This is derived from the truth table defined by NLF_CONSTANT = 0x3A5C742E
    """
    # ANF of NLF (computed from truth table)
    return (
        x1 + x0 +
        x4*x2 + x4*x0 +
        x3*x2 + x3*x0 +
        x2*x1 + x1*x0 +
        x4*x1*x0 + x4*x2*x0 +
        x4*x3*x1 + x4*x3*x2
    )


# =============================================================================
# Polygen-based equation generation (uses C implementation)
# =============================================================================

def generate_polygen_equations(
    plaintexts: List[int],
    ciphertexts: List[int],
    rounds: int,
    project_root: str = None,
    key_offsets: List[int] = None
) -> List[str]:
    """
    Generate KeeLoq equations using the C polygen implementation.
    
    This mirrors the equation format in polygen.c:
    - EQ1: L_i_j + constant (for plaintext/ciphertext constraints)
    - EQ2: Round function with NLF expanded
    - EQ3: a_i_j + L_i_(j-1)*L_i_(j-6) (auxiliary)
    - EQ4: b_i_j + L_i_(j-1)*L_i_(j-31) (auxiliary)
    
    Args:
        plaintexts: List of plaintext values
        ciphertexts: List of ciphertext values
        rounds: Number of rounds
        project_root: Path to KeeLoq project root (for finding the C binary)
        key_offsets: List of key schedule offsets per pair (default: all 0)
    
    Returns:
        List of equation strings in polygen format
    """
    equations = []
    num_pairs = len(plaintexts)
    if key_offsets is None:
        key_offsets = [0] * num_pairs
    
    for i in range(num_pairs):
        pt = plaintexts[i]
        ct = ciphertexts[i]
        ko = key_offsets[i]
        
        # EQ1: Initial state = plaintext bits
        for j in range(32):
            bit = (pt >> j) & 1
            equations.append(f"L_{i}_{j} + {bit}")
        
        # Round function equations
        for j in range(32, rounds + 32):
            # EQ2: Main round equation (NLF expanded as ANF)
            # Matches exactly the format in polygen.c/polygen.h
            eq2 = (
                f"L_{i}_{j} + k_{((j-32) + ko) % 64} + L_{i}_{j-32} + L_{i}_{j-16} + L_{i}_{j-23}"
                f" + L_{i}_{j-31} + L_{i}_{j-1}*L_{i}_{j-12} + b_{i}_{j} + L_{i}_{j-6}*L_{i}_{j-12}"
                f" + L_{i}_{j-6}*L_{i}_{j-31} + L_{i}_{j-12}*L_{i}_{j-23} + L_{i}_{j-23}*L_{i}_{j-31}"
                f" + b_{i}_{j}*L_{i}_{j-23} + b_{i}_{j}*L_{i}_{j-12} + a_{i}_{j}*L_{i}_{j-23} + a_{i}_{j}*L_{i}_{j-12}"
            )
            equations.append(eq2)
            
            # EQ3: Auxiliary variable a
            equations.append(f"a_{i}_{j} + L_{i}_{j-1}*L_{i}_{j-6}")
            
            # EQ4: Auxiliary variable b  
            equations.append(f"b_{i}_{j} + L_{i}_{j-1}*L_{i}_{j-31}")
        
        # EQ1: Final state = ciphertext bits
        for j in range(rounds, rounds + 32):
            bit = (ct >> (j - rounds)) & 1
            equations.append(f"L_{i}_{j} + {bit}")
    
    return equations


def parse_polygen_equations(equations: List[str], rounds: int, num_pairs: int):
    """
    Parse polygen equation strings and build a polynomial system.
    
    Args:
        equations: List of equation strings from polygen
        rounds: Number of rounds
        num_pairs: Number of P/C pairs
    
    Returns:
        ring: BooleanPolynomialRing
        polys: List of polynomials
        key_names: Key variable names
    """
    # Collect all variable names from the equations
    var_pattern = re.compile(r'[Lkab]_?\d+(?:_\d+)?')
    all_vars = set()
    
    for eq in equations:
        matches = var_pattern.findall(eq)
        all_vars.update(matches)
    
    # Categorize variables
    key_vars = sorted([v for v in all_vars if v.startswith('k_')], 
                      key=lambda x: int(x.split('_')[1]))
    L_vars = sorted([v for v in all_vars if v.startswith('L_')],
                    key=lambda x: (int(x.split('_')[1]), int(x.split('_')[2])))
    a_vars = sorted([v for v in all_vars if v.startswith('a_')],
                    key=lambda x: (int(x.split('_')[1]), int(x.split('_')[2])))
    b_vars = sorted([v for v in all_vars if v.startswith('b_')],
                    key=lambda x: (int(x.split('_')[1]), int(x.split('_')[2])))
    
    # Create ordered variable list (key vars first for extraction)
    all_var_names = key_vars + L_vars + a_vars + b_vars
    
    # Create Boolean polynomial ring
    ring = BooleanPolynomialRing(len(all_var_names), all_var_names)
    var_dict = {str(v): v for v in ring.gens()}
    
    # Parse equations into polynomials
    polys = []
    for eq_str in equations:
        poly = parse_equation_to_poly(eq_str, ring, var_dict)
        if poly is not None:
            polys.append(poly)
    
    return ring, polys, key_vars


def parse_equation_to_poly(eq_str: str, ring, var_dict):
    """
    Parse a single polygen equation string into a polynomial.
    
    Handles formats like:
    - "L_0_0 + 1"
    - "L_0_32 + k_0 + L_0_0 + L_0_16 + L_0_9*L_0_1 + ..."
    """
    # Replace variable names with ring generators
    # Split by + and process each term
    terms = [t.strip() for t in eq_str.split('+')]
    
    poly = ring.zero()
    
    for term in terms:
        if not term:
            continue
        
        # Check if it's a constant
        if term.isdigit():
            if int(term) == 1:
                poly += ring.one()
            continue
        
        # Parse product of variables (e.g., "L_0_1*L_0_6")
        factors = term.split('*')
        term_poly = ring.one()
        
        for factor in factors:
            factor = factor.strip()
            if factor in var_dict:
                term_poly *= var_dict[factor]
            elif factor.isdigit():
                if int(factor) == 0:
                    term_poly = ring.zero()
                    break
            else:
                # Unknown variable - skip this equation
                return None
        
        poly += term_poly
    
    return poly


def build_keeloq_system(
    plaintexts: list,
    ciphertexts: list,
    rounds: int,
    use_boolean_ring: bool = True,
    key_offsets: list = None
):
    """
    Build the polynomial system for KeeLoq over GF(2).
    
    Supports multiple plaintext-ciphertext pairs for better key recovery.
    
    Variables:
        - k_0, ..., k_63: key bits (shared across all pairs)
        - L_p_0, ..., L_p_{31+rounds}: state bits for pair p
    
    Args:
        plaintexts: list of plaintext values
        ciphertexts: list of ciphertext values  
        rounds: number of rounds per constraint
        use_boolean_ring: use BooleanPolynomialRing (default True)
        key_offsets: list of key schedule offsets per pair (default: all 0)
    
    Returns:
        ring: polynomial ring
        polys: list of polynomials
        key_vars: key variable names for solution extraction
    """
    num_pairs = len(plaintexts)
    num_state_vars = 32 + rounds
    if key_offsets is None:
        key_offsets = [0] * num_pairs
    
    # Variable names: key vars shared, state vars per pair
    key_names = [f'k{i}' for i in range(64)]
    state_names = []
    for p in range(num_pairs):
        state_names.extend([f'L{p}_{i}' for i in range(num_state_vars)])
    all_names = key_names + state_names
    
    # Create ring over GF(2)
    if use_boolean_ring:
        # BooleanPolynomialRing automatically enforces x^2 = x
        ring = BooleanPolynomialRing(len(all_names), all_names)
    else:
        ring = PolynomialRing(GF(2), all_names)
    
    # Get variables
    gens = ring.gens()
    k = gens[:64]  # key bits (shared)
    
    polys = []
    
    # Build constraints for each plaintext-ciphertext pair
    for p in range(num_pairs):
        # State variables for this pair
        offset = 64 + p * num_state_vars
        L = gens[offset:offset + num_state_vars]
        
        plaintext = plaintexts[p]
        ciphertext = ciphertexts[p]
        
        # Initial state constraints (plaintext bits)
        for j in range(32):
            pt_bit = (plaintext >> j) & 1
            polys.append(L[j] + pt_bit)
        
        # Round function equations
        for i in range(rounds):
            j = 32 + i  # current state index
            
            # NLF inputs (bit positions in state)
            x4 = L[j - 1]      # bit 31 of previous state
            x3 = L[j - 6]      # bit 26
            x2 = L[j - 12]     # bit 20
            x1 = L[j - 23]     # bit 9
            x0 = L[j - 31]     # bit 1
            
            # NLF output
            nlf_poly = create_nlf_polynomial(ring, x4, x3, x2, x1, x0)
            
            # Key bit (cyclic, with per-pair offset)
            key_bit = k[(i + key_offsets[p]) % 64]
            
            # Feedback: new_bit = k[i] + L[16] + L[0] + NLF
            feedback = key_bit + L[j - 16] + L[j - 32] + nlf_poly
            
            # After shift: L[j] is the new MSB (bit 31)
            polys.append(L[j] + feedback)
        
        # Final state constraints (ciphertext bits)
        for j in range(32):
            ct_bit = (ciphertext >> j) & 1
            state_idx = rounds + j  # L[rounds] to L[rounds+31]
            polys.append(L[state_idx] + ct_bit)
    
    return ring, polys, key_names


def solve_with_groebner(ring, polys, key_names, verbose: bool = True, target_key: int = None):
    """
    Solve the polynomial system using Groebner basis.
    
    Returns the recovered key if successful, None otherwise.
    """
    if verbose:
        print(f"Building ideal with {len(polys)} polynomials...")
    
    # Create ideal
    I = Ideal(polys)
    
    if verbose:
        print("Computing Groebner basis (this may take a while)...")
    
    start = time.time()
    
    # Compute Groebner basis
    try:
        G = I.groebner_basis()
    except Exception as e:
        print(f"Groebner basis computation failed: {e}")
        return None
    
    elapsed = time.time() - start
    
    if verbose:
        print(f"Groebner basis computed in {elapsed:.2f}s")
        print(f"Basis has {len(G)} polynomials")
    
    # Check if system has a solution (basis != [1])
    if len(G) == 1 and G[0] == 1:
        if verbose:
            print("System is inconsistent (no solution)")
        return None
    
    # Extract key bits from univariate polynomials in the Groebner basis
    # Supports both naming conventions: k0 (default) and k_0 (polygen)
    key_bits = {}
    
    for poly in G:
        poly_vars = poly.variables()
        if len(poly_vars) == 1:
            var = poly_vars[0]
            var_str = str(var)
            
            # Try both naming conventions
            idx = None
            if var_str.startswith('k_') and var_str[2:].isdigit():
                # Polygen format: k_0, k_1, ...
                idx = int(var_str[2:])
            elif var_str.startswith('k') and var_str[1:].isdigit():
                # Default format: k0, k1, ...
                idx = int(var_str[1:])
            
            if idx is not None:
                # poly = ki + c, where c is constant
                # poly = 0 => ki = c
                constant = poly.constant_coefficient()
                key_bits[idx] = int(constant)
    
    if verbose:
        print(f"Recovered {len(key_bits)}/64 key bits from basis")
        if key_bits:
            # Show which bits we recovered
            recovered = sorted(key_bits.keys())
            print(f"Recovered bit indices: {recovered[:10]}{'...' if len(recovered) > 10 else ''}")
    
    # Verify partial recovery against target key if provided
    if key_bits and target_key is not None:
        correct = sum(1 for i, b in key_bits.items() if ((target_key >> i) & 1) == b)
        if verbose:
            print(f"Verification: {correct}/{len(key_bits)} recovered bits match target key")
    
    if len(key_bits) == 64:
        key = sum(bit << i for i, bit in key_bits.items())
        return key
    
    if verbose and len(key_bits) < 64:
        print("System underdetermined - try more rounds or multiple P/C pairs")
    
    return None


def main():
    if not SAGE_AVAILABLE:
        sys.exit(1)
    
    parser = argparse.ArgumentParser(
        description='KeeLoq key recovery using Groebner basis (passagemath)'
    )
    parser.add_argument(
        '--rounds', '-r', type=int, default=32,
        help='Number of rounds (default: 32, full KeeLoq uses 528)'
    )
    parser.add_argument(
        '--pairs', '-n', type=int, default=1,
        help='Number of plaintext-ciphertext pairs (default: 1)'
    )
    parser.add_argument(
        '--key', '-k', type=lambda x: int(x, 0), default=0x5CEC6701B79FD949,
        help='Secret key for verification (default: test vector key)'
    )
    parser.add_argument(
        '--use-polygen', '-p', action='store_true',
        help='Use equations generated by C polygen (instead of Python implementation)'
    )
    parser.add_argument(
        '--verbose', '-v', action='store_true', default=True,
        help='Verbose output'
    )
    parser.add_argument(
        '--slide528', action='store_true',
        help='Slide528 mode: two 64-round constraints with key offsets 0 and 16'
    )
    
    args = parser.parse_args()
    
    # Generate random plaintexts and compute ciphertexts
    import random
    random.seed(42)  # reproducible
    
    if args.slide528:
        # Slide528 mode: generate a slid pair
        args.rounds = 64  # Force 64 rounds per constraint
        P1 = random.randint(0, 0xFFFFFFFF)
        P2 = keeloq_encrypt(args.key, P1, 64)   # P2 = E_64(K, P1)
        C1 = keeloq_encrypt(args.key, P1, 528)   # C1 = E_528(K, P1)
        C2 = keeloq_encrypt(args.key, P2, 528)   # C2 = E_528(K, P2)
        
        # Constraint 0: E_64(K, P1) = P2 with key offset 0
        # Constraint 1: E'_64(K, C1) = C2 with key offset 16
        plaintexts = [P1, C1]
        ciphertexts = [P2, C2]
        key_offsets = [0, 16]
        
        print("=" * 60)
        print("KeeLoq Groebner Basis Attack (Slide528 Mode)")
        print("=" * 60)
        print(f"Target key: 0x{args.key:016X}")
        print(f"Equations:  {'polygen (C)' if args.use_polygen else 'Python (default)'}")
        print(f"  P1=0x{P1:08X}, P2=0x{P2:08X} (E_64, key offset 0)")
        print(f"  C1=0x{C1:08X}, C2=0x{C2:08X} (E'_64, key offset 16)")
        print("=" * 60)
    else:
        plaintexts = [random.randint(0, 0xFFFFFFFF) for _ in range(args.pairs)]
        ciphertexts = [keeloq_encrypt(args.key, pt, args.rounds) for pt in plaintexts]
        key_offsets = None
        
        print("=" * 60)
        print("KeeLoq Groebner Basis Attack (passagemath)")
        print("=" * 60)
        print(f"Rounds:     {args.rounds}")
        print(f"P/C pairs:  {args.pairs}")
        print(f"Target key: 0x{args.key:016X}")
        print(f"Equations:  {'polygen (C)' if args.use_polygen else 'Python (default)'}")
        for i, (pt, ct) in enumerate(zip(plaintexts, ciphertexts)):
            print(f"  Pair {i}: P=0x{pt:08X} -> C=0x{ct:08X}")
        print("=" * 60)
    
    num_pairs = len(plaintexts)
    
    # Build polynomial system using the selected method
    print("\nBuilding polynomial system over GF(2)...")
    
    if args.use_polygen:
        # Use polygen-style equations (with auxiliary variables a, b)
        print("(Using polygen equation format)")
        eq_strings = generate_polygen_equations(
            plaintexts, ciphertexts, args.rounds, key_offsets=key_offsets
        )
        print(f"Generated {len(eq_strings)} equation strings")
        
        ring, polys, key_names = parse_polygen_equations(
            eq_strings, args.rounds, num_pairs
        )
        num_vars = len(ring.gens())
        print(f"Variables: {num_vars} (64 key + state + auxiliary)")
        print(f"Equations: {len(polys)}")
    else:
        # Use default Python implementation
        ring, polys, key_names = build_keeloq_system(
            plaintexts, ciphertexts, args.rounds, key_offsets=key_offsets
        )
        num_state = num_pairs * (32 + args.rounds)
        print(f"Variables: 64 key bits + {num_state} state bits ({num_pairs} pairs)")
        print(f"Equations: {len(polys)}")
    
    # Solve
    print("\nSolving with Groebner basis...")
    recovered_key = solve_with_groebner(ring, polys, key_names, args.verbose, args.key)
    
    print("\n" + "=" * 60)
    if recovered_key is not None:
        print(f"RECOVERED KEY: 0x{recovered_key:016X}")
        
        # Verify: does this key produce the correct ciphertexts?
        all_match = True
        if args.slide528:
            # In slide528 mode, verify with full 528-round encryption
            P1_orig = plaintexts[0]
            P2_orig = ciphertexts[0]
            # Check: E_528(K, P1) should give the same C1 we used
            C1_computed = keeloq_encrypt(recovered_key, P1_orig, 528)
            C2_computed = keeloq_encrypt(recovered_key, P2_orig, 528)
            all_match = (C1_computed == plaintexts[1] and C2_computed == ciphertexts[1])
        else:
            for pt, expected_ct in zip(plaintexts, ciphertexts):
                computed_ct = keeloq_encrypt(recovered_key, pt, args.rounds)
                if computed_ct != expected_ct:
                    all_match = False
                    break
        
        if all_match:
            print("VERIFIED: Recovered key produces correct ciphertexts!")
            if recovered_key == args.key:
                print("(Key matches target)")
            else:
                print("(Different from target - multiple valid keys exist)")
        else:
            print("ERROR: Recovered key does NOT produce correct ciphertexts!")
    else:
        print("FAILED: Could not recover key")
        print("Try more P/C pairs with --pairs or reducing rounds with --rounds")
    print("=" * 60)
    
    return recovered_key


if __name__ == '__main__':
    main()
